### ISSUE TITLE
[BUG] Space is omitted

### ISSUE THREAD

**Issue by yetanotheraccountforanonymity** [Wendelstein7/DiscordUnitCorrector#18]
##  Description

When receiving a message such as 
`string 1 pound`
, the bot will correctly correct it. However, the space between `string` and `1` will be omitted as follows:
`string454 g`.

## Fixes

I assume that this is a result of bad regex somewhere. 
The cheap, scuffed fix would be to just add a space. 
Another fix that depends on the user is to use 2 spaces.
Nonetheless, it is an inconvenience.

**Comment by UpsetDavid** [comment]
Bump, this is still a problem. Here is what it looks like.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/57288936/108410617-42fd0c80-71ed-11eb-808a-eae6ec1860fa.png">

**Comment by Shaquu** [comment]
@yetanotheraccountforanonymity  and @UpsetDavid I have added a PR for fixing the issue

**Comment by Wendelstein7** [comment]
The previously mentioned PR has just - way overdue - been tested, approved and merged!

**Comment by Randall-Scharpf** [comment]
Hello all

I was looking over the code, and noticed that the way the fix is applied, it should fail when the number contains a decimal point.
So I ran the following tests:
![image](https://user-images.githubusercontent.com/43557842/124053446-43ed4880-d9ee-11eb-8ba5-ebe13c03991c.png)
This shows that the bug I believed to be present does in fact exist.

I think there's a number of fixes that could solve this. The regex used now is `^ \d*[ ]?$`. I believe changing it to `^ \d*(\.\d*)?[ ]?$`, `^ \d*[ ]?`, `^ \d*`, or `^ ` would all work, however, I think a more robust and efficient solution could be formed using a loop over the characters in the number string.

Can this issue be reopened?
